### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [Cryptocoder2017/prj-rev-bwfs-dasmoto#8]
Satisfactory 👍 

Great job reproducing the web page according to the design mock. You've written some very efficient CSS as well, good job!

Practice writing classes and IDs more strategically. If several sections of the page are basically the same section, it's probably a good idea to give them the same class name. Like a `product` section, for example. Then you can write most of your shared styles in terms of `.product` and that will make it easier to maintain your site as it becomes larger and more complex.

**Comment by Cryptocoder2017** [comment]
Thanks for the feedback Steve. I will definitely look to take your advice about IDs and classes on the next project. Cheers!
